ProducaoAPI/Producao-MVC/Controllers/ProdutoController.cs
using Microsoft.AspNetCore.Mvc;
using Producao_MVC.Requests;
using Producao_MVC.Services;

namespace Producao_MVC.Controllers
{
    public class ProdutoController : Controller
    {
        private readonly ProdutoAPI _produtoAPI;

        public ProdutoController(ProdutoAPI produtoAPI)
        {
            _produtoAPI = produtoAPI;
        }

        public async Task<IActionResult> Index()
        {
            var produtos = await _produtoAPI.ListarProdutos();
            return View(produtos);
        }
        public IActionResult Criar()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> CriarProduto(ProdutoRequest request)
        {
            try
            {
                await _produtoAPI.CriarProduto(request);
                TempData["MensagemSucesso"] = "Produto cadastrado com sucesso";
                return RedirectToAction("Index");
            }
            catch (Exception erro)
            {
                TempData["MensagemErro"] = $"Não conseguimos cadastrar o seu produto. Erro: {erro.Message}";
                return View("Criar");
            }
        }

        public async Task<IActionResult> Editar(int id)
        {
            var produto = await _produtoAPI.BuscarProdutoPorID(id);
            return View(produto);
        }

        [HttpPost]
        public async Task<IActionResult> Editar(int id, ProdutoRequest request)
        {
            try
            {
                await _produtoAPI.AtualizarProduto(id, request);
                TempData["MensagemSucesso"] = "Produto alterado com sucesso";
                return RedirectToAction("Index");
            }
            catch (Exception erro)
            {
                TempData["MensagemErro"] = $"Não conseguimos atualizar o produto. Erro: {erro.Message}";
                return View();
            }
        }

        public async Task<IActionResult> Inativar(int id)
        {
            try
            {
                var produto = await _produtoAPI.BuscarProdutoPorID(id);
                return View(produto);
            }
            catch (Exception erro)
            {
                TempData["MensagemErro"] = $"Não conseguimos atualizar o produto. Erro: {erro.Message}";
                return RedirectToAction("Index");
            }
        }

        public async Task<IActionResult> InativarProduto(int id)
        {
            await _produtoAPI.InativarProduto(id);
            TempData["MensagemSucesso"] = "Produto inativado com sucesso";
            return RedirectToAction("Index");
        }
    }
}

ProducaoAPI/Producao-MVC/Views/Produto/Criar.cshtml
@model Producao_MVC.Requests.ProdutoRequest
@{
    ViewData["Title"] = "Criar Produto";
}

<div class="text-center">

    <h1 class="display-4">Cadastrar Produto</h1>

    @if (TempData["MensagemErro"] != null)
    {
        <div class="alert alert-danger" role="alert">
            @TempData["MensagemErro"]
        </div>
    }
</div>

<form asp-controller="Produto" asp-action="CriarProduto" method="post">

    <div class="form-group">
        <label for="nome">Nome</label>
        <input type="text" asp-for="Nome" class="form-control" placeholder="Digite o nome do produto">
        <span asp-validation-for="Nome" class="text-danger"></span>
    </div>
    <br/>
    <div class="form-group">
        <label for="medidas">Medidas</label>
        <input type="text" asp-for="Medidas" class="form-control" placeholder="Digite as medidas do produto">
        <span asp-validation-for="Medidas" class="text-danger"></span>
    </div>
    <br />
    <div class="form-group">
        <label for="unidade">Unidade</label>
        <input type="text" asp-for="Unidade" class="form-control" placeholder="Digite a unidade do produto">
        <span asp-validation-for="Unidade" class="text-danger"></span>
    </div>
    <br />
    <div class="form-group">
        <label for="pecasPorUnidade">Peças por Unidade</label>
        <input type="number" asp-for="PecasPorUnidade" class="form-control" placeholder="Digite o número de peças por unidade do produto">
        <span asp-validation-for="PecasPorUnidade" class="text-danger"></span>
    </div>
    <br />
    <button type="submit" class="btn btn-primary btn-block">Adicionar</button>
    <a class="btn btn-secondary btn-block" asp-controller="Produto" asp-action="Index" role="button">Voltar</a>
</form>

ProducaoAPI/Producao-MVC/Views/Produto/Editar.cshtml
@model Producao_MVC.Responses.ProdutoResponse

@{
    ViewData["Title"] = "Editar Produto";
}

<div class="text-center">

    <h1 class="display-4">Editar Produto</h1>

    @if (TempData["MensagemErro"] != null)
    {
        <div class="alert alert-danger" role="alert">
            @TempData["MensagemErro"]
        </div>
    }
</div>

<form asp-controller="Produto" asp-action="Editar" method="post">
    <input type="hidden" asp-for="Id" />
    <div class="form-group">
        <label for="nome">Nome</label>
        <input type="text" asp-for="Nome" class="form-control" placeholder="Digite o nome do produto">
        <span asp-validation-for="Nome" class="text-danger"></span>
    </div>
    <br />
    <div class="form-group">
        <label for="medidas">Medidas</label>
        <input type="text" asp-for="Medidas" class="form-control" placeholder="Digite as medidas do produto">
        <span asp-validation-for="Medidas" class="text-danger"></span>
    </div>
    <br />
    <div class="form-group">
        <label for="unidade">Unidade</label>
        <input type="text" asp-for="Unidade" class="form-control" placeholder="Digite a unidade do produto">
        <span asp-validation-for="Unidade" class="text-danger"></span>
    </div>
    <br />
    <div class="form-group">
        <label for="pecasPorUnidade">Peças por Unidade</label>
        <input type="number" asp-for="PecasPorUnidade" class="form-control" placeholder="Digite o número de peças por unidade do produto">
        <span asp-validation-for="PecasPorUnidade" class="text-danger"></span>
    </div>
    <br />
    <button type="submit" class="btn btn-primary btn-block">Editar</button>
    <a class="btn btn-secondary btn-block" asp-controller="Produto" asp-action="Index" role="button">Voltar</a>
</form>

ProducaoAPI/Producao-MVC/Views/Produto/Inativar.cshtml
@model Producao_MVC.Responses.ProdutoResponse

@{
    ViewData["Title"] = "Inativar Produto";
}

<div class="text">
    <h3>Realmente deseja inativar o produto (@Model.Nome)?</h3>
</div>
<br />
<a class="btn btn-primary btn-block" role="button" asp-controller="Produto" asp-action="Index">Cancelar exclusão</a>
<a class="btn btn-danger btn-block" role="button" asp-controller="Produto" asp-action="InativarProduto" asp-route-id="@Model.Id">Confirmar exclusão</a>

ProducaoAPI/Producao-MVC/Views/Produto/Index.cshtml
@model List<Producao_MVC.Responses.ProdutoResponse>

@{
    ViewData["Title"] = "Produtos";
}

<div class="text-center">

    <div class="d-grid gap-2 d-md-flex justify-content-md-start">
        <a class="btn btn-primary" role="button" asp-controller="Produto" asp-action="Criar">Adicionar Novo Produto</a>
    </div>
    <br />

    @if (TempData["MensagemSucesso"] != null)
    {
        <div class="alert alert-success" role="alert">
            @TempData["MensagemSucesso"]
        </div>
    }

    @if (TempData["MensagemErro"] != null)
    {
        <div class="alert alert-danger" role="alert">
            @TempData["MensagemErro"]
        </div>
    }

    <h1 class="display-4">Listagem de Produtos</h1>

    <table id="table-produtos" class="display" style="width:100%">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Nome</th>
                <th scope="col">Medidas</th>
                <th scope="col">Unidade</th>
                <th scope="col">Peças por Unidade</th>
                <th scope="col"></th>
            </tr>
        </thead>
        <tbody>
            @if (Model != null && Model.Any())
            {
                foreach (var produto in Model)
                {
                    <tr>
                        <th scope="row">@produto.Id</th>
                        <td>@produto.Nome</td>
                        <td>@produto.Medidas</td>
                        <td>@produto.Unidade</td>
                        <td>@produto.PecasPorUnidade</td>
                        <td class="column-action-buttons">
                            <div class="btn-group" role="group">
                                <a role="button" class="btn btn-primary" asp-route-id="@produto.Id" asp-controller="Produto" asp-action="Editar">Editar</a>
                                <a role="button" class="btn btn-danger" asp-route-id="@produto.Id" asp-controller="Produto" asp-action="Inativar">Apagar</a>
                            </div>
                        </td>
                    </tr>
                }
            }
            else
            {
                <tr class="odd"><td valign="top" colspan="5">Nenhum produto encontrado</td></tr>
            }
        </tbody>
    </table>
</div>