ProducaoAPI/Producao-MVC/Controllers/FormaController.cs
using Microsoft.AspNetCore.Mvc;
using Producao_MVC.Models;
using Producao_MVC.Requests;
using Producao_MVC.Responses;
using Producao_MVC.Services;

namespace Producao_MVC.Controllers
{
    public class FormaController : Controller
    {
        private readonly FormaAPI _formaApi;
        private readonly MaquinaAPI _maquinaApi;
        private readonly ProdutoAPI _produtoAPI;

        public FormaController(FormaAPI formaApi, MaquinaAPI maquinaApi, ProdutoAPI produtoAPI)
        {
            _formaApi = formaApi;
            _maquinaApi = maquinaApi;
            _produtoAPI = produtoAPI;
        }

        public async Task<IActionResult> Index()
        {
            var formas = await _formaApi.ListarFormas();
            return View(formas);
        }

        public async Task<IActionResult> Criar()
        {
            try
            {
                return View(await RetornarViewModel(false));
            }
            catch (Exception erro)
            {
                TempData["MensagemErro"] = $"Algo deu errado. Erro: {erro.Message}";
                return RedirectToAction("Index");
            }
        }

        [HttpPost]
        public async Task<IActionResult> Criar(FormaProdutoViewModel formaViewModel)
        {
            try
            {
                var forma = await CriarFormaPorModelo(formaViewModel);
                await _formaApi.CriarForma(forma);
                TempData["MensagemSucesso"] = "Forma cadastrada com sucesso";
                return RedirectToAction("Index");
            }
            catch (Exception erro)
            {
                TempData["MensagemErro"] = $"Não conseguimos cadastrar a sua forma. Erro: {erro.Message}";
                return View(await RetornarViewModel(false));
            }
        }

        public async Task<IActionResult> Editar(int id)
        {
            try
            {
                return View(await RetornarViewModel(true, id));
            }
            catch (Exception erro)
            {
                TempData["MensagemErro"] = $"Algo deu errado. Erro: {erro.Message}";
                return RedirectToAction("Index");
            }
        }

        [HttpPost]
        public async Task<IActionResult> Editar(FormaProdutoViewModel formaViewModel)
        {
            try
            {
                List<FormaMaquinaRequest> maquinasSelecionadas = [];
                foreach (var item in formaViewModel.MaquinasCheckbox)
                {
                    if (item.Selecionado)
                    {
                        maquinasSelecionadas.Add(new FormaMaquinaRequest(item.Id));
                    }
                }

                var request = new FormaRequest(formaViewModel.Nome, formaViewModel.ProdutoId, formaViewModel.PecasPorCiclo, maquinasSelecionadas);
                await _formaApi.AtualizarForma(formaViewModel.Forma.Id, request);

                TempData["MensagemSucesso"] = "Forma alterada com sucesso";
                return RedirectToAction("Index");
            }
            catch (Exception erro)
            {
                TempData["MensagemErro"] = $"Não conseguimos atualizar a forma. Erro: {erro.Message}";
                return View(await RetornarViewModel(true, formaViewModel.Forma.Id));
            }
        }

        public async Task<IActionResult> Inativar(int id)
        {
            try
            {
                var forma = await _formaApi.BuscarFormaPorID(id);
                return View(forma);
            }
            catch (Exception erro)
            {
                TempData["MensagemErro"] = $"Algo deu errado. Erro: {erro.Message}";
                return RedirectToAction("Index");
            }
        }

        public async Task<IActionResult> InativarForma(int id)
        {
            try
            {
                await _formaApi.InativarForma(id);
                TempData["MensagemSucesso"] = "Forma inativada com sucesso";
                return RedirectToAction("Index");
            }
            catch (Exception erro)
            {
                TempData["MensagemErro"] = $"Não conseguimos atualizar a forma. Erro: {erro.Message}";
                return RedirectToAction("Index");
            }
        }

        private async Task<FormaRequest> CriarFormaPorModelo(FormaProdutoViewModel formaViewModel)
        {
            List<MaquinaResponse> maquinasSelecionadas = [];
            foreach (var item in formaViewModel.MaquinasCheckbox)
            {
                if (item.Selecionado)
                {
                    maquinasSelecionadas.Add(await _maquinaApi.BuscarMaquinaPorID(item.Id));
                }
            }

            List<FormaMaquinaRequest> formaMaquinasRequest = [];
            foreach (var item in maquinasSelecionadas)
            {
                formaMaquinasRequest.Add(new FormaMaquinaRequest(item.Id));
            }

            var formaRequest = new FormaRequest(formaViewModel.Nome, formaViewModel.ProdutoId, formaViewModel.PecasPorCiclo, formaMaquinasRequest);
            return formaRequest;
        }

        private async Task<FormaProdutoViewModel> RetornarViewModel(bool Editar, int id = 0)
        {
            var produtos = await _produtoAPI.ListarProdutos();
            var maquinas = await _maquinaApi.ListarMaquinas();

            var maquinasCheckbox = new List<MaquinaCheckboxViewModel>();
            foreach (var maquina in maquinas)
            {
                maquinasCheckbox.Add(new MaquinaCheckboxViewModel
                {
                    Id = maquina.Id,
                    Nome = maquina.Nome,
                    Selecionado = false
                });
            }

            if (Editar)
            {
                var forma = await _formaApi.BuscarFormaPorID(id);
                var maquinasDaForma = forma.Maquinas.ToList();

                for (int i = 0; i < maquinasCheckbox.Count; i++)
                {
                    var maquina = await _maquinaApi.BuscarMaquinaPorID(maquinasCheckbox[i].Id);
                    if (maquinasDaForma.Contains(maquina))
                    {
                        maquinasCheckbox[i].Selecionado = true;
                    }
                }

                return new FormaProdutoViewModel
                {
                    Forma = forma,
                    Nome = forma.Nome,
                    ProdutoId = forma.Produto.Id,
                    PecasPorCiclo = forma.PecasPorCiclo,
                    Maquinas = maquinas.ToList(),
                    MaquinasCheckbox = maquinasCheckbox,
                    Produtos = produtos
                };
            }
            else
            {
                return new FormaProdutoViewModel
                {
                    Produtos = produtos,
                    Maquinas = maquinas.ToList(),
                    MaquinasCheckbox = maquinasCheckbox,
                };
            }
        }
    }
}

ProducaoAPI/Producao-MVC/Views/Forma/Criar.cshtml
@model FormaProdutoViewModel

@{
    ViewData["Title"] = "Criar Forma";
}

<div class="text-center">

    <h1 class="display-4">Cadastrar Forma</h1>

    @if (TempData["MensagemErro"] != null)
    {
        <div class="alert alert-danger" role="alert">
            @TempData["MensagemErro"]
        </div>
    }
</div>

<form asp-controller="Forma" asp-action="Criar" method="post">

    <div class="form-group">
        <label for="nome">Nome</label>
        <input type="text" asp-for="Nome" class="form-control" placeholder="Digite o nome da forma">
        <span asp-validation-for="Nome" class="text-danger"></span>
    </div>
    <br />
    <div>
        <label for="Produto">Produto</label>
        <select asp-for="ProdutoId" class="form-control">
            <option value="">Selecione um produto</option>
            @foreach (var produto in Model.Produtos)
            {
                <option value="@produto.Id">@produto.Nome</option>
            }
        </select>
        <span asp-validation-for="ProdutoId" class="text-danger"></span>
    </div>
    <br />
    <div>
        <label for="Maquinas">Maquinas</label>
        <table class="table-estilizada">
            <tbody>
                @for (int i = 0; i < Model.Maquinas.Count; i++)
                {
                    <tr>
                        <td id="th-td-criar-forma">
                            <input asp-for="@Model.MaquinasCheckbox[i].Selecionado" type="checkbox"  />
                            <input asp-for="@Model.MaquinasCheckbox[i].Id" type="hidden" />
                        </td>
                        <td id="th-td-criar-forma">@Model.Maquinas[i].Nome</td>
                    </tr>
                }
            </tbody>
        </table>
        <span asp-validation-for="MaquinasCheckbox" class="text-danger"></span>
    </div>
    <br />
    <div class="form-group">
        <label for="pecasPorCiclo">Peças por Ciclo</label>
        <input type="number" asp-for="PecasPorCiclo" class="form-control" placeholder="Digite o número de peças por ciclo da forma">
        <span asp-validation-for="PecasPorCiclo" class="text-danger"></span>
    </div>
    <br />

    <button type="submit" class="btn btn-primary btn-block">Adicionar</button>
    <a class="btn btn-secondary btn-block" asp-controller="Forma" asp-action="Index" role="button">Voltar</a>
</form>

ProducaoAPI/Producao-MVC/Views/Forma/Editar.cshtml
@model FormaProdutoViewModel

@{
    ViewData["Title"] = "Editar Forma";
}

<div class="text-center">

    <h1 class="display-4">Editar Forma</h1>

    @if (TempData["MensagemErro"] != null)
    {
        <div class="alert alert-danger" role="alert">
            @TempData["MensagemErro"]
        </div>
    }
</div>

<form asp-controller="Forma" asp-action="Editar" method="post">
    <input type="hidden" asp-for="Forma.Id" />
    <div class="form-group">
        <label for="nome">Nome</label>
        <input type="text" asp-for="Nome" class="form-control" placeholder="Digite o nome da forma">
        <span asp-validation-for="Nome" class="text-danger"></span>
    </div>
    <div>
        <label for="Produto">Produto</label>
        <select asp-for="ProdutoId" class="form-control">
            <option value="">Selecione um produto</option>
            @foreach (var produto in Model.Produtos)
            {
                <option value="@produto.Id">@produto.Nome</option>
            }
        </select>
        <span asp-validation-for="ProdutoId" class="text-danger"></span>
    </div>
    <br />
    <div>
        <label for="Maquinas">Maquinas</label>
        <table class="table-estilizada">
            <tbody>
                @for (int i = 0; i < Model.Maquinas.Count; i++)
                {
                    <tr>
                        <td id="th-td-criar-forma">
                            <input asp-for="@Model.MaquinasCheckbox[i].Selecionado" type="checkbox" />
                            <input asp-for="@Model.MaquinasCheckbox[i].Id" type="hidden" />
                        </td>
                        <td id="th-td-criar-forma">@Model.Maquinas[i].Nome</td>
                    </tr>
                }
            </tbody>
        </table>
        <span asp-validation-for="MaquinasCheckbox" class="text-danger"></span>
        <br />
    </div>
    <div class="form-group">
        <label for="pecasPorCiclo">Peças por Ciclo</label>
        <input type="number" asp-for="PecasPorCiclo" class="form-control" placeholder="Digite o número de peças por ciclo da forma">
        <span asp-validation-for="PecasPorCiclo" class="text-danger"></span>
    </div>
    <br />
    <button type="submit" class="btn btn-primary btn-block">Editar</button>
    <a class="btn btn-secondary btn-block" asp-controller="Forma" asp-action="Index" role="button">Voltar</a>
</form>

ProducaoAPI/Producao-MVC/Views/Forma/Inativar.cshtml
@model Producao_MVC.Responses.FormaResponse

@{
    ViewData["Title"] = "Inativar Forma";
}

<div class="text">
    <h3>Realmente deseja inativar a forma (@Model.Nome)?</h3>
</div>

<a class="btn btn-primary btn-block" role="button" asp-controller="Forma" asp-action="Index">Cancelar exclusão</a>
<a class="btn btn-danger btn-block" role="button" asp-controller="Forma" asp-action="InativarForma" asp-route-id="@Model.Id">Confirmar exclusão</a>

ProducaoAPI/Producao-MVC/Views/Forma/InativarConfirmacao.cshtml
@model Producao_MVC.Responses.FormaResponse

@{
    ViewData["Title"] = "Inativar Forma";
}

<div class="text">
    <h3>Realmente deseja inativar a forma (@Model.Nome)?</h3>
</div>

<a class="btn btn-primary btn-block" role="button" asp-controller="Forma" asp-action="Index">Cancelar exclusão</a>
<a class="btn btn-danger btn-block" role="button" asp-controller="Forma" asp-action="Inativar" asp-route-id="@Model.Id">Confirmar exclusão</a>

ProducaoAPI/Producao-MVC/Views/Forma/Index.cshtml
@model List<Producao_MVC.Responses.FormaResponse>

@{
    ViewData["Title"] = "Formas";
}

<div class="text-center">

    <div class="d-grid gap-2 d-md-flex justify-content-md-start">
        <a class="btn btn-primary" role="button" asp-controller="Forma" asp-action="Criar">Adicionar Nova Forma</a>
    </div>
    <br />

    @if (TempData["MensagemSucesso"] != null)
    {
        <div class="alert alert-success" role="alert">
            @TempData["MensagemSucesso"]
        </div>
    }

    @if (TempData["MensagemErro"] != null)
    {
        <div class="alert alert-danger" role="alert">
            @TempData["MensagemErro"]
        </div>
    }

    <h1 class="display-4">Listagem de Formas</h1>

    <table id="table-formas" class="display" style="width:100%">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Nome</th>
                <th scope="col">Produto</th>
                <th scope="col">Peças por Ciclo</th>
                <th scope="col">Maquinas</th>
                <th scope="col"></th>
            </tr>
        </thead>
        <tbody>
            @if (Model != null && Model.Any())
            {
                foreach (Producao_MVC.Responses.FormaResponse forma in Model)
                {
                    <tr>
                        <th scope="row">@forma.Id</th>
                        <td>@forma.Nome</td>
                        <td>@forma.Produto.Nome</td>
                        <td>@forma.PecasPorCiclo</td>
                        <td>
                            @foreach (Producao_MVC.Responses.MaquinaResponse maquina in forma.Maquinas)
                            {
                                @maquina.Nome
                            }
                        </td>
                        <td class="column-action-buttons">
                            <div class="btn-group" role="group">
                                <a role="button" class="btn btn-primary" asp-route-id="@forma.Id" asp-controller="Forma" asp-action="Editar">Editar</a>
                                <a role="button" class="btn btn-danger" asp-route-id="@forma.Id" asp-controller="Forma" asp-action="Inativar">Inativar</a>
                            </div>
                        </td>
                    </tr>
                }
            }
            else
            {
                <tr class="odd"><td valign="top" colspan="5">Nenhuma forma encontrada</td></tr>
            }
        </tbody>
    </table>
</div>