ProducaoAPI/Producao-MVC/Models/ProcessoProducaoViewModel.cs
using Producao_MVC.Responses;
using System.ComponentModel.DataAnnotations;

namespace Producao_MVC.Models
{
    public class ProcessoProducaoViewModel
    {
        public ProcessoProducaoResponse Producao { get; set; }
        public DateTime Data { get; set; }
        public List<MaquinaResponse> Maquinas { get; set; }
        public List<FormaResponse> Formas { get; set; }
        public List<ProdutoResponse> Produtos { get; set; }
        public List<MateriaPrimaResponse> MateriasPrimas { get; set; }
        [Required(ErrorMessage = "A máquina é obrigatória.")]
        public int MaquinaId { get; set; }
        [Required(ErrorMessage = "A forma é obrigatória.")]
        public int FormaId { get; set; }
        [Required(ErrorMessage = "O produto é obrigatório.")]
        public int ProdutoId { get; set; }
        [Required(ErrorMessage = "O número de ciclos é obrigatório.")]
        [Range(1, 10000, ErrorMessage = "O número de ciclos deve ser maior do que 0.")]
        public int Ciclos { get; set; }
        [Required(ErrorMessage = "A lista de matérias-primas não pode ser vazia.")]
        public List<MateriaPrimaCheckboxViewModel> MateriasPrimasCheckbox { get; set; }
    }
}

ProducaoAPI/Producao-MVC/Controllers/ProcessoProducaoController.cs
using Microsoft.AspNetCore.Mvc;
using Producao_MVC.Models;
using Producao_MVC.Requests;
using Producao_MVC.Responses;
using Producao_MVC.Services;

namespace Producao_MVC.Controllers
{
    public class ProcessoProducaoController : Controller
    {
        private readonly ProcessoProducaoAPI _processoProducaoAPI;
        private readonly MaquinaAPI _maquinaAPI;
        private readonly FormaAPI _formaAPI;
        private readonly ProdutoAPI _produtoAPI;
        private readonly MateriaPrimaAPI _materiaPrimaAPI;

        public ProcessoProducaoController(ProcessoProducaoAPI processoProducaoAPI, MaquinaAPI maquinaAPI, FormaAPI formaAPI, ProdutoAPI produtoAPI, MateriaPrimaAPI materiaPrimaAPI)
        {
            _processoProducaoAPI = processoProducaoAPI;
            _maquinaAPI = maquinaAPI;
            _formaAPI = formaAPI;
            _produtoAPI = produtoAPI;
            _materiaPrimaAPI = materiaPrimaAPI;
        }

        public async Task<IActionResult> Index()
        {
            var producoes = await _processoProducaoAPI.ListarProcessosProducoes();
            return View(producoes);
        }
        public async Task<IActionResult> Criar()
        {
            var maquinas = await _maquinaAPI.ListarMaquinas();
            var formas = await _formaAPI.ListarFormas();
            var produtos = await _produtoAPI.ListarProdutos();
            var materiasPrimas = await _materiaPrimaAPI.ListarMateriasPrimas();

            var materiasCheckbox = new List<MateriaPrimaCheckboxViewModel>();

            foreach (var materia in materiasPrimas)
            {
                var materiaCheck = new MateriaPrimaCheckboxViewModel
                {
                    Id = materia.Id,
                    Nome = materia.Nome,
                    Selecionado = false,
                    Quantidade = 0
                };
                materiasCheckbox.Add(materiaCheck);
            }

            var viewModel = new ProcessoProducaoViewModel
            {
                Maquinas = maquinas.ToList(),
                Formas = formas.ToList(),
                Produtos = produtos.ToList(),
                MateriasPrimas = materiasPrimas.ToList(),
                MateriasPrimasCheckbox = materiasCheckbox
            };

            return View(viewModel);
        }
        
        public async Task CriarProducaoPorModelo(ProcessoProducaoViewModel request)
        {
            List<MateriaPrimaResponse> materiasSelecionadas = new();
            List<ProcessoProducaoMateriaPrimaRequest> producaoMateriaPrimas = new();

            foreach (var item in request.MateriasPrimasCheckbox)
            {
                if (item.Selecionado)
                {
                    materiasSelecionadas.Add(await _materiaPrimaAPI.BuscarMateriaPrimaPorID(item.Id));
                }
            }

            for (int i = 0; i < materiasSelecionadas.Count; i++)
            {
                producaoMateriaPrimas.Add(new ProcessoProducaoMateriaPrimaRequest(materiasSelecionadas[i].Id, request.MateriasPrimasCheckbox[i].Quantidade));
            };

            var producao = new ProcessoProducaoRequest(request.Data, request.MaquinaId, request.FormaId, request.Ciclos, producaoMateriaPrimas);
            await _processoProducaoAPI.CriarProcessoProducao(producao);
        }

        [HttpPost]
        public IActionResult Criar(ProcessoProducaoViewModel producaoVm)
        {
            try
            {
                var producao = CriarProducaoPorModelo(producaoVm);
                TempData["MensagemSucesso"] = "Produção cadastrada com sucesso";
                return RedirectToAction("Index");
            }
            catch (Exception erro)
            {
                TempData["MensagemErro"] = $"Não conseguimos cadastrar a produção, tente novamente, detalhe do erro: {erro.Message}";
                return RedirectToAction("Index");
            }
        }

        public async Task<IActionResult> Editar(int id)
        {
            var producao = await _processoProducaoAPI.BuscarProcessoProducaoPorID(id);
            var maquinas = await _maquinaAPI.ListarMaquinas();
            var formas = await _formaAPI.ListarFormas();
            var produtos = await _produtoAPI.ListarProdutos();
            var materiasPrimas = await _materiaPrimaAPI.ListarMateriasPrimas();

            var materiasPrimasDaProducao = producao.ProducaoMateriasPrimas.ToList();
            var materiasCheckbox = new List<MateriaPrimaCheckboxViewModel>();

            foreach (var materia in materiasPrimas)
            {
                var materiaCheck = new MateriaPrimaCheckboxViewModel
                {
                    Id = materia.Id,
                    Nome = materia.Nome,
                    Selecionado = false,
                    Quantidade = 0
                };
                materiasCheckbox.Add(materiaCheck);
            }

            for (int i = 0; i < materiasCheckbox.Count; i++)
            {

                foreach (var item in materiasPrimasDaProducao)
                {
                    if (item.MateriaPrimaId == materiasCheckbox[i].Id)
                    {
                        materiasCheckbox[i].Selecionado = true;
                        materiasCheckbox[i].Quantidade = item.Quantidade;
                    }
                }
            }

            var viewModel = new ProcessoProducaoViewModel
            {
                Producao = producao,
                Data = producao.Data,
                MaquinaId = producao.MaquinaId,
                Maquinas = maquinas.ToList(),
                FormaId = producao.FormaId,
                Formas = formas.ToList(),
                Produtos = produtos.ToList(),
                Ciclos = producao.Ciclos,
                MateriasPrimas = materiasPrimas.ToList(),
                MateriasPrimasCheckbox = materiasCheckbox
            };

            return View(viewModel);
        }

        [HttpPost]
        public async Task<IActionResult> EditarProducao(ProcessoProducaoViewModel producaoVM)
        {
            try
            {
                List<ProcessoProducaoMateriaPrimaRequest> producaoMateriaPrimas = new();

                foreach (var item in producaoVM.MateriasPrimasCheckbox)
                {
                    if (item.Selecionado)
                    {
                        producaoMateriaPrimas.Add(new ProcessoProducaoMateriaPrimaRequest(item.Id, item.Quantidade));
                    }
                }

                var request = new ProcessoProducaoRequest(producaoVM.Data, producaoVM.MaquinaId, producaoVM.FormaId, producaoVM.Ciclos, producaoMateriaPrimas);

                await _processoProducaoAPI.AtualizarProcessoProducao(producaoVM.Producao.Id, request);
                TempData["MensagemSucesso"] = "Produção alterada com sucesso";
                return RedirectToAction("Index");
            }
            catch (Exception erro)
            {
                TempData["MensagemErro"] = $"Não conseguimos atualizar a produção, tente novamente, detalhe do erro: {erro.Message}";
                return RedirectToAction("Index");
            }
        }

        public async Task<IActionResult> Inativar(int id)
        {
            var producao = await _processoProducaoAPI.BuscarProcessoProducaoPorID(id);
            return View(producao);
        }

        public async Task<IActionResult> InativarProducao(int id)
        {
            await _processoProducaoAPI.InativarProcessoProducao(id);
            TempData["MensagemSucesso"] = "Produção inativada com sucesso";
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> CalcularProducao(int id)
        {
            await _processoProducaoAPI.CalcularProducao(id);
            TempData["MensagemSucesso"] = "Produção calculada com sucesso";
            return RedirectToAction("Index");
        }
    }
}

ProducaoAPI/Producao-MVC/Views/ProcessoProducao/Criar.cshtml
@model ProcessoProducaoViewModel

@{
    ViewData["Title"] = "Criar Produção";
}

<div class="text-center">

    <h1 class="display-4">Cadastrar Produção</h1>

</div>

<form asp-controller="ProcessoProducao" asp-action="Criar" method="post">

    <div class="form-group">
        <label for="data">Data</label>
        <input type="date" asp-for="Data" class="form-control" placeholder="Digite a data da produção">
        <span asp-validation-for="Data" class="text-danger"></span>
    </div>
    <br />
    <div>
        <label for="maquina">Máquina</label>
        <select asp-for="MaquinaId" class="form-control">
            <option value="">Selecione uma máquina</option>
            @foreach (var maquina in Model.Maquinas)
            {
                <option value="@maquina.Id">@maquina.Nome</option>
            }
        </select>
        <span asp-validation-for="MaquinaId" class="text-danger"></span>
    </div>
    <br />
    <div>
        <label for="forma">Forma e Produto</label>
        <select asp-for="FormaId" class="form-control">
            <option value="">Selecione uma forma</option>
            @foreach (var forma in Model.Formas)
            {
                <option value="@forma.Id">@forma.Nome - (@forma.Produto.Nome)</option>
            }
        </select>
        <span asp-validation-for="FormaId" class="text-danger"></span>
    </div>
    <br />
    <div class="form-group">
        <label for="ciclos">Ciclos</label>
        <input type="number" asp-for="Ciclos" class="form-control" placeholder="Digite o número de ciclos">
        <span asp-validation-for="Ciclos" class="text-danger"></span>
    </div>
    <br />
    <div>
        <label for="MateriasPrimas">Matérias-Primas</label>
        <table class="table-estilizada">
            <thead>
                <tr>
                    <th></th>
                    <th></th>
                    <th>Quantidade</th>
                </tr>
            </thead>
            <tbody>
                @for (int i = 0; i < Model.MateriasPrimas.Count; i++)
                {
                    <tr>
                        <td>
                            <input asp-for="@Model.MateriasPrimasCheckbox[i].Selecionado" type="checkbox" />
                            <input asp-for="@Model.MateriasPrimasCheckbox[i].Id" type="hidden" />
                        </td>
                        <td>@Model.MateriasPrimas[i].Nome</td>
                        <td><input type="number" step="0.01" placeholder="0.00" asp-for="@Model.MateriasPrimasCheckbox[i].Quantidade" class="form-control" /></td>
                    </tr>
                }
            </tbody>
        </table>
        <br />
    </div>

    <button type="submit" class="btn btn-primary btn-block">Adicionar</button>
    <a class="btn btn-secondary btn-block" asp-controller="ProcessoProducao" asp-action="Index" role="button">Voltar</a>
</form>

ProducaoAPI/Producao-MVC/Views/ProcessoProducao/Editar.cshtml
@model ProcessoProducaoViewModel

@{
    ViewData["Title"] = "Editar Produção";
}

<div class="text-center">

    <h1 class="display-4">Editar Produção</h1>

</div>

<form asp-controller="ProcessoProducao" asp-action="EditarProducao" method="post">
    <input type="hidden" asp-for="Producao.Id" />
    <div class="form-group">
        <label for="data">Data</label>
        <input type="date" asp-for="Data" class="form-control" placeholder="Digite a data da produção">
        <span asp-validation-for="Data" class="text-danger"></span>
    </div>
    <br />
    <div>
        <label for="maquina">Máquina</label>
        <select asp-for="MaquinaId" class="form-control">
            <option value="">Selecione uma máquina</option>
            @foreach (var maquina in Model.Maquinas)
            {
                <option value="@maquina.Id">@maquina.Nome</option>
            }
        </select>
        <span asp-validation-for="MaquinaId" class="text-danger"></span>
    </div>
    <br />
    <div>
        <label for="forma">Forma e Produto</label>
        <select asp-for="FormaId" class="form-control">
            <option value="">Selecione uma forma</option>
            @foreach (var forma in Model.Formas)
            {
                <option value="@forma.Id">@forma.Nome - (@forma.Produto.Nome)</option>
            }
        </select>
        <span asp-validation-for="FormaId" class="text-danger"></span>
    </div>
    <br />
    <div class="form-group">
        <label for="ciclos">Ciclos</label>
        <input type="number" asp-for="Ciclos" class="form-control" placeholder="Digite o número de ciclos">
        <span asp-validation-for="Ciclos" class="text-danger"></span>
    </div>
    <br />
    <div>
        <label for="MateriasPrimas">Matérias-Primas</label>
        <table class="table-estilizada">
            <thead>
                <tr>
                    <th></th>
                    <th></th>
                    <th>Quantidade</th>
                </tr>
            </thead>
            <tbody>
                @for (int i = 0; i < Model.MateriasPrimas.Count; i++)
                {
                    <tr>
                        <td>
                            <input asp-for="@Model.MateriasPrimasCheckbox[i].Selecionado" type="checkbox" />
                            <input asp-for="@Model.MateriasPrimasCheckbox[i].Id" type="hidden" />
                        </td>
                        <td>@Model.MateriasPrimas[i].Nome</td>
                        <td><input type="number" step="0.01" placeholder="0.00" asp-for="@Model.MateriasPrimasCheckbox[i].Quantidade" class="form-control" /></td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
    <br/>
    <button type="submit" class="btn btn-primary btn-block">Editar</button>
    <a class="btn btn-secondary btn-block" asp-controller="ProcessoProducao" asp-action="Index" role="button">Voltar</a>
</form>

ProducaoAPI/Producao-MVC/Views/ProcessoProducao/Inativar.cshtml
@model Producao_MVC.Responses.ProcessoProducaoResponse

@{
    ViewData["Title"] = "Inativar Produção";
}

<div class="text">
    <h3>Realmente deseja inativar a produção ID (@Model.Id)? (Data @Model.Data.Date)</h3>
</div>
<br />
<a class="btn btn-primary btn-block" role="button" asp-controller="ProcessoProducao" asp-action="Index">Cancelar exclusão</a>
<a class="btn btn-danger btn-block" role="button" asp-controller="ProcessoProducao" asp-action="InativarProducao" asp-route-id="@Model.Id">Confirmar exclusão</a>

ProducaoAPI/Producao-MVC/Views/ProcessoProducao/Index.cshtml
@model List<Producao_MVC.Responses.ProcessoProducaoResponse>

@{
    ViewData["Title"] = "Produções";
}

<div class="text-center">

    <div class="d-grid gap-2 d-md-flex justify-content-md-start">
        <a class="btn btn-primary" role="button" asp-controller="ProcessoProducao" asp-action="Criar">Adicionar Nova Produção</a>
    </div>
    <br />

    @if (TempData["MensagemSucesso"] != null)
    {
        <div class="alert alert-success" role="alert">
            @TempData["MensagemSucesso"]
        </div>
    }

    @if (TempData["MensagemErro"] != null)
    {
        <div class="alert alert-danger" role="alert">
            @TempData["MensagemErro"]
        </div>
    }

    <h1 class="display-4">Listagem de Produções</h1>

    <table class="table table-responsive">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Data</th>
                <th scope="col">Maquina</th>
                <th scope="col">Forma</th>
                <th scope="col">Produto</th>
                <th scope="col">Ciclos</th>
                <th scope="col">Quantidade Produzida</th>
                <th scope="col">Matérias-Primas</th>
                <th scope="col">Quantidade</th>
                <th scope="col">Custo Unitário</th>
                <th scope="col">Custo Total</th>
                <th scope="col"></th>
            </tr>
        </thead>
        <tbody>
            @if (Model != null && Model.Any())
            {
                foreach (var producao in Model)
                {
                    <tr>
                        <th scope="row">@producao.Id</th>
                        <td>@producao.Data.Date</td>
                        <td>@producao.MaquinaId</td>
                        <td>@producao.FormaId</td>
                        <td></td>
                        <td>@producao.Ciclos</td>
                        <td>@Math.Round(Convert.ToDecimal(producao.QuantidadeProduzida), 2)</td>
                        <td>
                            @foreach (var materiaPrima in producao.ProducaoMateriasPrimas)
                            {
                                @materiaPrima.NomeMateriaPrima
                                <br />
                            }
                        </td>
                        <td>
                            @foreach (var materiaPrima in producao.ProducaoMateriasPrimas)
                            {
                                @materiaPrima.Quantidade
                                <br />
                            }
                        </td>
                        <td>R$ @Math.Round(Convert.ToDecimal(@producao.CustoUnitario), 2)</td>
                        <td>R$ @Math.Round(Convert.ToDecimal(@producao.CustoTotal), 2)</td>
                        <td class="column-action-buttons">
                            <div class="btn-group" role="group">
                                <a role="button" class="btn btn-success" asp-route-id="@producao.Id" asp-controller="ProcessoProducao" asp-action="CalcularProducao">Calcular</a>
                                <a role="button" class="btn btn-primary" asp-route-id="@producao.Id" asp-controller="ProcessoProducao" asp-action="Editar">Editar</a>
                                <a role="button" class="btn btn-danger" asp-route-id="@producao.Id" asp-controller="ProcessoProducao" asp-action="Inativar">Inativar</a>
                            </div>
                        </td>
                    </tr>
                }
            }
            else
            {
                <tr class="odd"><td valign="top" colspan="5">Nenhuma produção encontrada</td></tr>
            }
        </tbody>
    </table>
    
</div>