ProducaoAPI/Producao-MVC/Controllers/MateriaPrimaController.cs
using Microsoft.AspNetCore.Mvc;
using Producao_MVC.Requests;
using Producao_MVC.Services;

namespace Producao_MVC.Controllers
{
    public class MateriaPrimaController : Controller
    {
        private readonly MateriaPrimaAPI _materiaPrimaAPI;

        public MateriaPrimaController(MateriaPrimaAPI materiaPrimaAPI)
        {
            _materiaPrimaAPI = materiaPrimaAPI;
        }

        public async Task<IActionResult> Index()
        {
            var materiasPrimas = await _materiaPrimaAPI.ListarMateriasPrimas();
            return View(materiasPrimas);
        }
        public IActionResult Criar()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> CriarMateriaPrima(MateriaPrimaRequest request)
        {
            try
            {
                await _materiaPrimaAPI.CriarMateriaPrima(request);
                TempData["MensagemSucesso"] = "Matéria-prima cadastrada com sucesso";
                return RedirectToAction("Index");
            }
            catch (Exception erro)
            {
                TempData["MensagemErro"] = $"Não conseguimos cadastrar a sua matéria-prima. Erro: {erro.Message}";
                return View("Criar");
            }
        }

        public async Task<IActionResult> Editar(int id)
        {
            var materiaPrima = await _materiaPrimaAPI.BuscarMateriaPrimaPorID(id);
            return View(materiaPrima);
        }

        [HttpPost]
        public async Task<IActionResult> Editar(int id, MateriaPrimaRequest request)
        {
            try
            {
                await _materiaPrimaAPI.AtualizarMateriaPrima(id, request);
                TempData["MensagemSucesso"] = "Matéria-prima alterada com sucesso";
                return RedirectToAction("Index");
            }
            catch (Exception erro)
            {
                TempData["MensagemErro"] = $"Não conseguimos atualizar a matéria-prima. Erro: {erro.Message}";
                return View();
            }
        }

        public async Task<IActionResult> Inativar(int id)
        {
            try
            {
                var materiaPrima = await _materiaPrimaAPI.BuscarMateriaPrimaPorID(id);
                return View(materiaPrima);
            }
            catch (Exception erro)
            {
                TempData["MensagemErro"] = $"Não conseguimos atualizar a matéria-prima. Erro: {erro.Message}";
                return RedirectToAction("Index");
            }
        }

        public async Task<IActionResult> InativarMateriaPrima(int id)
        {
            await _materiaPrimaAPI.InativarMateriaPrima(id);
            TempData["MensagemSucesso"] = "Matéria-prima inativada com sucesso";
            return RedirectToAction("Index");
        }
    }
}

ProducaoAPI/Producao-MVC/Views/MateriaPrima/Criar.cshtml
@model Producao_MVC.Requests.MateriaPrimaRequest
@{
    ViewData["Title"] = "Criar Matéria-Prima";
}

<div class="text-center">

    <h1 class="display-4">Cadastrar Matéria-Prima</h1>

    @if (TempData["MensagemErro"] != null)
    {
        <div class="alert alert-danger" role="alert">
            @TempData["MensagemErro"]
        </div>
    }
</div>

<form asp-controller="MateriaPrima" asp-action="CriarMateriaPrima" method="post">

    <div class="form-group">
        <label for="nome">Nome</label>
        <input type="text" asp-for="Nome" class="form-control" placeholder="Digite o nome da matéria-prima">
        <span asp-validation-for="Nome" class="text-danger"></span>
    </div>
    <br />
    <div class="form-group">
        <label for="medidas">Fornecedor</label>
        <input type="text" asp-for="Fornecedor" class="form-control" placeholder="Digite o fornecedor da matéria-prima">
        <span asp-validation-for="Fornecedor" class="text-danger"></span>
    </div>
    <br />
    <div class="form-group">
        <label for="unidade">Unidade</label>
        <input type="text" asp-for="Unidade" class="form-control" placeholder="Digite a unidade da matéria-prima">
        <span asp-validation-for="Unidade" class="text-danger"></span>
    </div>
    <br />
    <div class="form-group">
        <label for="preco">Preço</label>
        <input type="number" step="0.01" placeholder="0.00" asp-for="Preco" class="form-control" placeholder="Digite o preço da matéria-prima">
        <span asp-validation-for="Preco" class="text-danger"></span>
    </div>
    <br />
    <button type="submit" class="btn btn-primary btn-block">Adicionar</button>
    <a class="btn btn-secondary btn-block" asp-controller="MateriaPrima" asp-action="Index" role="button">Voltar</a>
</form>

ProducaoAPI/Producao-MVC/Views/MateriaPrima/Editar.cshtml
@model Producao_MVC.Responses.MateriaPrimaResponse

@{
    ViewData["Title"] = "Editar Matéria-Prima";
}

<div class="text-center">

    <h1 class="display-4">Editar Matéria-Prima</h1>

    @if (TempData["MensagemErro"] != null)
    {
        <div class="alert alert-danger" role="alert">
            @TempData["MensagemErro"]
        </div>
    }
</div>

<form asp-controller="MateriaPrima" asp-action="Editar" method="post">
    <input type="hidden" asp-for="Id" />
    <div class="form-group">
        <label for="nome">Nome</label>
        <input type="text" asp-for="Nome" class="form-control" placeholder="Digite o nome da matéria-prima">
        <span asp-validation-for="Nome" class="text-danger"></span>
    </div>
    <br />
    <div class="form-group">
        <label for="medidas">Fornecedor</label>
        <input type="text" asp-for="Fornecedor" class="form-control" placeholder="Digite o fornecedor da matéria-prima">
        <span asp-validation-for="Fornecedor" class="text-danger"></span>
    </div>
    <br />
    <div class="form-group">
        <label for="unidade">Unidade</label>
        <input type="text" asp-for="Unidade" class="form-control" placeholder="Digite a unidade da matéria-prima">
        <span asp-validation-for="Unidade" class="text-danger"></span>
    </div>
    <br />
    <div class="form-group">
        <label for="pecasPorUnidade">Preço</label>
        <input type="number" asp-for="Preco" class="form-control" placeholder="Digite o preço da matéria-prima">
        <span asp-validation-for="Preco" class="text-danger"></span>
    </div>
    <br />
    <button type="submit" class="btn btn-primary btn-block">Editar</button>
    <a class="btn btn-secondary btn-block" asp-controller="MateriaPrima" asp-action="Index" role="button">Voltar</a>
</form>

ProducaoAPI/Producao-MVC/Views/MateriaPrima/Inativar.cshtml
@model Producao_MVC.Responses.MateriaPrimaResponse

@{
    ViewData["Title"] = "Inativar Matéria-Prima";
}

<div class="text">
    <h3>Realmente deseja inativar a matéria-prima (@Model.Nome)?</h3>
</div>
<br />
<a class="btn btn-primary btn-block" role="button" asp-controller="MateriaPrima" asp-action="Index">Cancelar exclusão</a>
<a class="btn btn-danger btn-block" role="button" asp-controller="MateriaPrima" asp-action="InativarMateriaPrima" asp-route-id="@Model.Id">Confirmar exclusão</a>

ProducaoAPI/Producao-MVC/Views/MateriaPrima/Index.cshtml
@model List<Producao_MVC.Responses.MateriaPrimaResponse>

@{
    ViewData["Title"] = "Matérias-Primas";
}

<div class="text-center">

    <div class="d-grid gap-2 d-md-flex justify-content-md-start">
        <a class="btn btn-primary" role="button" asp-controller="MateriaPrima" asp-action="Criar">Adicionar Nova Matéria-Prima</a>
    </div>
    <br />

    @if (TempData["MensagemSucesso"] != null)
    {
        <div class="alert alert-success" role="alert">
            @TempData["MensagemSucesso"]
        </div>
    }

    @if (TempData["MensagemErro"] != null)
    {
        <div class="alert alert-danger" role="alert">
            @TempData["MensagemErro"]
        </div>
    }

    <h1 class="display-4">Listagem de Matérias-Primas</h1>

    <table id="table-materiasPrimas" class="display" style="width:100%">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Nome</th>
                <th scope="col">Fornecedor</th>
                <th scope="col">Unidade</th>
                <th scope="col">Preço</th>
                <th scope="col"></th>
            </tr>
        </thead>
        <tbody>
            @if (Model != null && Model.Any())
            {
                foreach (var materiaPrima in Model)
                {
                    <tr>
                        <th scope="row">@materiaPrima.Id</th>
                        <td>@materiaPrima.Nome</td>
                        <td>@materiaPrima.Fornecedor</td>
                        <td>@materiaPrima.Unidade</td>
                        <td>R$ @materiaPrima.Preco</td>
                        <td class="column-action-buttons">
                            <div class="btn-group" role="group">
                                <a role="button" class="btn btn-primary" asp-route-id="@materiaPrima.Id" asp-controller="MateriaPrima" asp-action="Editar">Editar</a>
                                <a role="button" class="btn btn-danger" asp-route-id="@materiaPrima.Id" asp-controller="MateriaPrima" asp-action="Inativar">Inativar</a>
                            </div>
                        </td>
                    </tr>
                }
            }
            else
            {
                <tr class="odd"><td valign="top" colspan="5">Nenhuma matéria-prima encontrada</td></tr>
            }
        </tbody>
    </table>
</div>